export const UPDATE_TASK_LIST = 'updateTaskList'
export const UPDATE_EDIT_TASK = 'updateEditTask'
export const SET_DELETE_TASK_ID = 'setDeleteTaskId'
export const SET_SEARCH_TEXT = 'setSearchText'
export const UPDATE_SEARCH_RESULT = 'updateSearchResult'
export const SET_SEARCH_DATE = 'setSearchDate'
